version: "3.7"
services:
    api:
        build: .
        ports:
            - 3333:3333
        environment:
            MONGO_URI: mongodb://db/dinosaurs
            PORT: 3333
            ADMIN_PASSWORD: letmein
        depends_on:
            - db

    db:
        image: mongo
